spring.application.name=springio
spring.mvc.apiversion.default=1.1
spring.mvc.apiversion.use.header=X-API-VERSION

app.runners[0].name=r1
app.runners[0].type=t1
app.runners[0].properties.key1=v1
app.runners[0].properties.key2=v2
app.runners[1].name=r2
app.runners[1].type=t2
app.runners[1].properties.key3=v3
app.runners[1].properties.key4=v4

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.web=DEBUG

spring.threads.virtual.enabled=true

spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true