create table users
(
    id       bigint generated by default as identity primary key,
    username varchar(255) not null unique,  -- add NOT NULL if required
    password varchar(512) not null,
    enabled  boolean      not null default true,  -- default true for new users
    created_at timestamp default current_timestamp,  -- audit trail
    updated_at timestamp default current_timestamp
);

alter table users owner to neondb_owner;


create table authorities
(
    id        bigint generated by default as identity primary key,
    username  varchar(255) not null,
    authority VARCHAR(50)  NOT NULL,
    created_at timestamp default current_timestamp, -- audit trail
    updated_at timestamp default current_timestamp,
    constraint fk_authorities_users
        foreign key (username) references users (username)
);

create unique index ix_auth_username
    on authorities (username, authority);

create table groups
(
    id         bigint generated by default as identity primary key,
    group_name varchar(50) not null,
    created_at timestamp default current_timestamp, -- audit trail
    updated_at timestamp default current_timestamp
);

create table group_authorities
(
    id         bigint generated by default as identity primary key,
    group_id   bigint      not null,
    authority  varchar(50) not null,
    created_at timestamp default current_timestamp, -- audit trail
    updated_at timestamp default current_timestamp,
    constraint fk_group_authorities_group foreign key (group_id) references groups (id)
);

create table group_members
(
    id         bigint generated by default as identity primary key,
    username   varchar(50) not null,
    group_id   bigint      not null,
    created_at timestamp default current_timestamp, -- audit trail
    updated_at timestamp default current_timestamp,
    constraint fk_group_members_group foreign key (group_id) references groups (id)
);